import React from 'react';
import { Briefcase, Award, Gift, Users, Star } from 'lucide-react';

interface SponsorshipProps {
  language: string;
}

const Sponsorship: React.FC<SponsorshipProps> = ({ language }) => {
  const content = {
    pt: {
      title: 'Patrocínio',
      subtitle: 'Apoie nossas iniciativas e faça parte da transformação',
      intro: 'Ao se tornar um patrocinador de nossos projetos, sua organização se associa a valores de sustentabilidade, diversidade cultural e impacto social positivo, enquanto ganha visibilidade junto ao nosso público engajado.',
      why: {
        title: 'Por que patrocinar',
        reasons: [
          {
            title: 'Responsabilidade social',
            description: 'Demonstre o compromisso da sua marca com causas importantes e desenvolvimento sustentável',
            icon: <Award className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Visibilidade estratégica',
            description: 'Alcance um público qualificado, interessado em turismo responsável e cultura africana',
            icon: <Star className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Networking valioso',
            description: 'Conecte-se com outras organizações e profissionais comprometidos com o desenvolvimento africano',
            icon: <Users className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Impacto mensurável',
            description: 'Receba relatórios detalhados sobre os resultados e benefícios gerados pelo seu patrocínio',
            icon: <Briefcase className="w-8 h-8 text-orange-500" />
          }
        ]
      },
      projects: {
        title: 'Projetos para patrocínio',
        list: [
          'Manifesto',
          'Quem somos',
          'O projeto',
          'Impacto',
          'Mentorias',
          'Programas',
          'Parceiros',
          'Delá',
          'Favela Tech',
          'Kindezi BAL',
          'CGBW',
          'clipping',
          'Contato'
        ]
      },
      contact: 'Entre em contato para discutir oportunidades'
    },
    en: {
      title: 'Sponsorship',
      subtitle: 'Support our initiatives and be part of the transformation',
      intro: 'By becoming a sponsor of our projects, your organization associates itself with values of sustainability, cultural diversity, and positive social impact, while gaining visibility with our engaged audience.',
      why: {
        title: 'Why sponsor',
        reasons: [
          {
            title: 'Social responsibility',
            description: 'Demonstrate your brand\'s commitment to important causes and sustainable development',
            icon: <Award className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Strategic visibility',
            description: 'Reach a qualified audience interested in responsible tourism and African culture',
            icon: <Star className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Valuable networking',
            description: 'Connect with other organizations and professionals committed to African development',
            icon: <Users className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Measurable impact',
            description: 'Receive detailed reports on the results and benefits generated by your sponsorship',
            icon: <Briefcase className="w-8 h-8 text-orange-500" />
          }
        ]
      },
      projects: {
        title: 'Projects for sponsorship',
        list: [
          'Manifesto',
          'Quem somos',
          'O projeto',
          'Impacto',
          'Mentorias',
          'Programas',
          'Parceiros',
          'Delá',
          'Favela Tech',
          'Kindezi BAL',
          'CGBW',
          'clipping',
          'Contato'
        ]
      },
      contact: 'Contact us to discuss opportunities'
    }
  };

  const t = content[language as keyof typeof content];

  const handleScroll = (sectionName: string) => {
    const id = sectionName.toLowerCase().replace(/\s/g, '-'); // transforma "Quem somos" em "quem-somos"
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <section id="sponsorship" className="py-20 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4 text-gray-900">{t.title}</h2>
          <p className="text-xl text-gray-600">{t.subtitle}</p>
        </div>

        <div className="max-w-3xl mx-auto text-center mb-16">
          <Gift className="w-16 h-16 text-orange-500 mx-auto mb-8" />
          <p className="text-lg text-gray-700 leading-relaxed">
            {t.intro}
          </p>
        </div>

        <div className="mb-16">
          <h3 className="text-2xl font-bold mb-10 text-center text-gray-900">{t.why.title}</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {t.why.reasons.map((reason, index) => (
              <div
                key={index}
                className="bg-[#f4e3d7] rounded-xl p-8 shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1"
              >
                <div className="bg-orange-100 w-16 h-16 rounded-full flex items-center justify-center mb-6 mx-auto">
                  {reason.icon}
                </div>
                <h4 className="text-xl font-bold mb-3 text-gray-900 text-center">{reason.title}</h4>
                <p className="text-gray-600 text-center">{reason.description}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="grid md:grid-cols-5 gap-8 items-center mb-16">
          <div className="md:col-span-2">
            <div className="rounded-xl overflow-hidden shadow-lg">
              <img
                src="https://images.pexels.com/photos/3184422/pexels-photo-3184422.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750"
                alt="Sponsorship"
                className="w-full h-auto"
              />
            </div>
          </div>

          <div className="md:col-span-3">
            <h3 className="text-2xl font-bold mb-6 text-gray-900">{t.projects.title}</h3>
            <ul className="space-y-3 mb-8">
              {t.projects.list.map((project, index) => (
                <li
                  key={index}
                  className="flex items-start bg-[#f4e3d7] p-4 rounded-lg shadow-sm cursor-pointer hover:bg-orange-100 transition"
                  onClick={() => handleScroll(project)}
                >
                  <div className="mr-3 mt-1">
                    <div className="w-2 h-2 rounded-full bg-orange-500"></div>
                  </div>
                  <span className="text-gray-700">{project}</span>
                </li>
              ))}
            </ul>

            <div className="flex">
              <a
                href="#contact"
                className="flex-1 py-3 px-6 bg-orange-500 hover:bg-orange-600 text-white rounded-lg text-center transition-colors duration-300"
              >
                {t.contact}
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Sponsorship;
