import React from 'react';
import { Briefcase, Award, Gift, Users, Star, Check } from 'lucide-react';

interface SponsorshipProps {
  language: string;
}

const Sponsorship: React.FC<SponsorshipProps> = ({ language }) => {
  const content = {
    pt: {
      title: 'Patrocínio',
      subtitle: 'Apoie nossas iniciativas e faça parte da transformação',
      intro: 'Ao se tornar um patrocinador de nossos projetos, sua organização se associa a valores de sustentabilidade, diversidade cultural e impacto social positivo, enquanto ganha visibilidade junto ao nosso público engajado.',
      why: {
        title: 'Por que patrocinar',
        reasons: [
          {
            title: 'Responsabilidade social',
            description: 'Demonstre o compromisso da sua marca com causas importantes e desenvolvimento sustentável',
            icon: <Award className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Visibilidade estratégica',
            description: 'Alcance um público qualificado, interessado em turismo responsável e cultura africana',
            icon: <Star className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Networking valioso',
            description: 'Conecte-se com outras organizações e profissionais comprometidos com o desenvolvimento africano',
            icon: <Users className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Impacto mensurável',
            description: 'Receba relatórios detalhados sobre os resultados e benefícios gerados pelo seu patrocínio',
            icon: <Briefcase className="w-8 h-8 text-orange-500" />
          }
        ]
      },
      opportunities: {
        title: 'Oportunidades de patrocínio',
        list: [
          {
            name: 'Patrocinador Platinum',
            price: 'A partir de R$ 50.000',
            featured: true,
            benefits: [
              'Logo em posição de destaque em todos os materiais',
              'Menção em todas as comunicações oficiais',
              'Participação em eventos especiais',
              'Acesso exclusivo a relatórios de impacto',
              'Conteúdo personalizado para suas redes sociais',
              'Tour VIP para executivos e convidados'
            ]
          },
          {
            name: 'Patrocinador Gold',
            price: 'A partir de R$ 25.000',
            benefits: [
              'Logo em posição secundária em todos os materiais',
              'Menção em comunicações selecionadas',
              'Convites para eventos especiais',
              'Relatórios trimestrais de impacto',
              'Conteúdo para redes sociais'
            ]
          },
          {
            name: 'Patrocinador Silver',
            price: 'A partir de R$ 10.000',
            benefits: [
              'Logo em seção de patrocinadores',
              'Menção em newsletter mensal',
              'Convites para eventos anuais',
              'Relatório anual de impacto'
            ]
          }
        ]
      },
      projects: {
        title: 'Projetos para patrocínio',
        list: [
          'Centro Global de Biodiversidade Natural (CGBN)',
          'Biblioteca de Arte e Literatura Africana (Kindezi BAL)',
          'Programa de Turismo Comunitário (Favela)',
          'Projeto de Artesanato Dela',
          'Iniciativas educacionais e culturais'
        ]
      },
      contact: 'Entre em contato para discutir oportunidades',
      brochure: 'Baixar apresentação completa'
    },
    en: {
      title: 'Sponsorship',
      subtitle: 'Support our initiatives and be part of the transformation',
      intro: 'By becoming a sponsor of our projects, your organization associates itself with values of sustainability, cultural diversity, and positive social impact, while gaining visibility with our engaged audience.',
      why: {
        title: 'Why sponsor',
        reasons: [
          {
            title: 'Social responsibility',
            description: 'Demonstrate your brand\'s commitment to important causes and sustainable development',
            icon: <Award className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Strategic visibility',
            description: 'Reach a qualified audience interested in responsible tourism and African culture',
            icon: <Star className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Valuable networking',
            description: 'Connect with other organizations and professionals committed to African development',
            icon: <Users className="w-8 h-8 text-orange-500" />
          },
          {
            title: 'Measurable impact',
            description: 'Receive detailed reports on the results and benefits generated by your sponsorship',
            icon: <Briefcase className="w-8 h-8 text-orange-500" />
          }
        ]
      },
      opportunities: {
        title: 'Sponsorship opportunities',
        list: [
          {
            name: 'Platinum Sponsor',
            price: 'Starting from $10,000',
            featured: true,
            benefits: [
              'Logo in prominent position on all materials',
              'Mention in all official communications',
              'Participation in special events',
              'Exclusive access to impact reports',
              'Customized content for your social media',
              'VIP tour for executives and guests'
            ]
          },
          {
            name: 'Gold Sponsor',
            price: 'Starting from $5,000',
            benefits: [
              'Logo in secondary position on all materials',
              'Mention in selected communications',
              'Invitations to special events',
              'Quarterly impact reports',
              'Content for social media'
            ]
          },
          {
            name: 'Silver Sponsor',
            price: 'Starting from $2,000',
            benefits: [
              'Logo in sponsors section',
              'Mention in monthly newsletter',
              'Invitations to annual events',
              'Annual impact report'
            ]
          }
        ]
      },
      projects: {
        title: 'Projects for sponsorship',
        list: [
          'Global Center for Natural Biodiversity (GCNB)',
          'African Art and Literature Library (Kindezi BAL)',
          'Community Tourism Program (Favela)',
          'Dela Craft Project',
          'Educational and cultural initiatives'
        ]
      },
      contact: 'Contact us to discuss opportunities',
      brochure: 'Download complete presentation'
    }
  };

  const t = content[language as keyof typeof content];

  return (
    <section id="sponsorship" className="py-20 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4 text-gray-900">{t.title}</h2>
          <p className="text-xl text-gray-600">{t.subtitle}</p>
        </div>

        <div className="max-w-3xl mx-auto text-center mb-16">
          <Gift className="w-16 h-16 text-orange-500 mx-auto mb-8" />
          <p className="text-lg text-gray-700 leading-relaxed">
            {t.intro}
          </p>
        </div>

        <div className="mb-16">
          <h3 className="text-2xl font-bold mb-10 text-center text-gray-900">{t.why.title}</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {t.why.reasons.map((reason, index) => (
              <div 
                key={index}
                className="bg-white rounded-xl p-8 shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1"
              >
                <div className="bg-orange-100 w-16 h-16 rounded-full flex items-center justify-center mb-6 mx-auto">
                  {reason.icon}
                </div>
                <h4 className="text-xl font-bold mb-3 text-gray-900 text-center">{reason.title}</h4>
                <p className="text-gray-600 text-center">{reason.description}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mb-16">
          <h3 className="text-2xl font-bold mb-10 text-center text-gray-900">{t.opportunities.title}</h3>
          <div className="grid md:grid-cols-3 gap-8">
            {t.opportunities.list.map((tier, index) => (
              <div 
                key={index}
                className={`
                  rounded-xl p-8 transition-all duration-300 transform hover:-translate-y-2
                  ${tier.featured 
                    ? 'bg-orange-500 text-white shadow-lg ring-4 ring-orange-200 relative z-10 scale-105 my-4 md:my-0' 
                    : 'bg-white text-gray-900 shadow-md'}
                `}
              >
                <h4 className="text-2xl font-bold mb-2">{tier.name}</h4>
                <p className={`text-xl font-bold mb-6 ${tier.featured ? 'text-white' : 'text-orange-500'}`}>
                  {tier.price}
                </p>
                
                <ul className="space-y-3 mb-8">
                  {tier.benefits.map((benefit, i) => (
                    <li key={i} className="flex items-start">
                      <Check className={`w-5 h-5 mr-2 shrink-0 ${tier.featured ? 'text-white' : 'text-orange-500'}`} />
                      <span>{benefit}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        <div className="grid md:grid-cols-5 gap-8 items-center mb-16">
          <div className="md:col-span-2">
            <div className="rounded-xl overflow-hidden shadow-lg">
              <img 
                src="https://images.pexels.com/photos/3184422/pexels-photo-3184422.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750" 
                alt="Sponsorship" 
                className="w-full h-auto"
              />
            </div>
          </div>
          
          <div className="md:col-span-3">
            <h3 className="text-2xl font-bold mb-6 text-gray-900">{t.projects.title}</h3>
            <ul className="space-y-3 mb-8">
              {t.projects.list.map((project, index) => (
                <li key={index} className="flex items-start bg-white p-4 rounded-lg shadow-sm">
                  <div className="mr-3 mt-1">
                    <div className="w-2 h-2 rounded-full bg-orange-500"></div>
                  </div>
                  <span className="text-gray-700">{project}</span>
                </li>
              ))}
            </ul>

            <div className="flex flex-col sm:flex-row gap-4 mt-8">
              <a 
                href="#contact" 
                className="flex-1 py-3 px-6 bg-orange-500 hover:bg-orange-600 text-white rounded-lg text-center transition-colors duration-300"
              >
                {t.contact}
              </a>
              <a 
                href="#" 
                className="flex-1 py-3 px-6 border border-orange-500 text-orange-500 hover:bg-orange-50 rounded-lg text-center transition-colors duration-300"
              >
                {t.brochure}
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Sponsorship;